### ISSUE TITLE
Has children is not applied to top level items

### ISSUE THREAD

**Issue by durbanski** [roots/soil#214]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/soil/issues)
- [x] I've read the [README](https://github.com/roots/soil/blob/master/README.md) and followed its instructions (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**

Class `menu-item-has-children` is not added to menu items.

**What is the expected or desired behavior?**

Class `menu-item-has-children` should be added to menu items.

---

## Bug report

I saw this issue: https://github.com/roots/soil/issues/124

And this commit: https://github.com/roots/soil/commit/e9ef2742b6bc8d71d79c068c5983e59590779d8b

Unfortunately logic behid this code is wrong:

```php
if ($item->is_subitem) {
      $classes[] = 'menu-item-has-children';
}
```

It's because `is_subitem` does not tell us if given menu element has any childs or not. It only tells if current item is submenu item of another item.

So for example this is an item (top level item) which has subitems and its dump looks like this (see classes and is_subitem):

```php
/var/www/html/wp-content/plugins/soil/modules/nav-walker.php:80:
object(WP_Post)[1198]
  public 'ID' => int 93
  public 'post_author' => string '1' (length=1)
  public 'post_date' => string '2018-11-20 11:46:08' (length=19)
  public 'post_date_gmt' => string '2018-11-20 11:46:08' (length=19)
  public 'post_content' => string ' ' (length=1)
  public 'post_title' => string '' (length=0)
  public 'post_excerpt' => string '' (length=0)
  public 'post_status' => string 'publish' (length=7)
  public 'comment_status' => string 'closed' (length=6)
  public 'ping_status' => string 'closed' (length=6)
  public 'post_password' => string '' (length=0)
  public 'post_name' => string '93' (length=2)
  public 'to_ping' => string '' (length=0)
  public 'pinged' => string '' (length=0)
  public 'post_modified' => string '2018-11-20 12:27:58' (length=19)
  public 'post_modified_gmt' => string '2018-11-20 12:27:58' (length=19)
  public 'post_content_filtered' => string '' (length=0)
  public 'post_parent' => int 0
  public 'guid' => string '//localhost:3001/?p=93' (length=29)
  public 'menu_order' => int 2
  public 'post_type' => string 'nav_menu_item' (length=13)
  public 'post_mime_type' => string '' (length=0)
  public 'comment_count' => string '0' (length=1)
  public 'filter' => string 'raw' (length=3)
  public 'db_id' => int 93
  public 'menu_item_parent' => string '0' (length=1)
  public 'object_id' => string '7' (length=1)
  public 'object' => string 'page' (length=4)
  public 'type' => string 'post_type' (length=9)
  public 'type_label' => string 'Page' (length=4)
  public 'url' => string '//localhost:3001/solutions/' (length=34)
  public 'title' => string 'Solutions' (length=9)
  public 'target' => string '' (length=0)
  public 'attr_title' => string '' (length=0)
  public 'description' => string '' (length=0)
  public 'classes' => 
    array (size=5)
      0 => string '' (length=0)
      1 => string 'menu-item' (length=9)
      2 => string 'menu-item-type-post_type' (length=24)
      3 => string 'menu-item-object-page' (length=21)
      4 => string 'menu-item-has-children' (length=22)
  public 'xfn' => string '' (length=0)
  public 'current' => boolean false
  public 'current_item_ancestor' => boolean false
  public 'current_item_parent' => boolean false
  public 'is_subitem' => boolean false
  public 'is_active' => boolean false
```

As far as i can tell, there is no other way of checking whether item has subitems other than checking `classes` array if `menu-item-has-children` class exists.

```php
if (in_array('menu-item-has-children', $item->classes)) {
      $classes[] = 'menu-item-has-children';
}
```

**Please describe your local environment:**

Soil version: 3.7.3
WordPress version: 4.9.8
Active theme: custom
Active plugins: Soil

**Comment by durbanski** [comment]
@mmirus 

You are right!

Indeed I used depth => 1 and it seems to be the issue.

Still, it feels odd to me that WordPress itself recognizes that this menu item should have `menu-item-has-children` even if depth is set to 1, but at the same time, it has `is_subitem` is `false`.

In my case, I actually print only the first level of navigation and the rest is custom JSON based mobile experience. That's why I need some indicators of which elements have some interaction behind it.

This is so specific that I forked the plugin just for this so I guess it is not the issue at all.

Thanks!

**Comment by mmirus** [comment]
Hey @durbanski,

Glad we were able to figure out what the issue was.

IMO the `is_subitem` term itself isn't as clear as it could be, given its usage--something like `is_parent` or `has_children` might be clearer. There may have been good reasons for using that term when Soil was being written (e.g., perhaps it's a convention elsewhere), though.

That said, it doesn't help you in this case, but I actually think Soil's behavior here makes more sense than WordPress' behavior.

There are two senses of 'has children' we could consider here:

1. Does the item have children as defined in the menu settings?
2. Does the item have children *that will be used in the current menu instance* (i.e., that meet the depth requirements)?

Soil's behavior is to only report that the item has children when the item's children will actually be used in the current instance of the menu.

This has a benefit as a practical matter:

Testing the same menu (with a max_depth of 1) on the Twenty Seventeen theme without Soil causes the parent menu item to be styled as a dropdown, but doesn't include the child item--it's an empty dropdown. Basically, it can't decide whether or not the item has children and breaks down halfway in between. Since Soil omits the class, the resulting markup accurately reflects the state of the rendered menu, fixing that display problem.
