### ISSUE TITLE
soil-clean breaks new page

### ISSUE THREAD

**Issue by jordan314** [roots/soil#234]
This is similar to #220 which is closed. We are unable to create a new page with soil enabled. I've tracked this down to soil-clean, which replaces 's with ". Gutenberg's wp.apiFetch.use( wp.apiFetch.createPreloadingMiddleware({})) uses quotes in a javascript object, so this replaces apostrophes with unescaped quotes which breaks the javascript object which breaks the editor.

**Comment by retlehs** [comment]
if you cannot use soil with gutenberg then it sounds like you're using an outdated version. you can grab the latest from https://roots.io/product-links/

soil does not run in the admin whatsoever and has not since soil 3.7.2 (Jun 11, 2017)

if you have further issues, please post on https://discourse.roots.io for support
