### ISSUE TITLE
Move all JS to footer

### ISSUE THREAD

**Issue by austinpray** [roots/soil#33]
Continuation from https://github.com/roots/roots/issues/1148#issuecomment-59640699

Hello guys,

I understand this has been attempted before over at https://github.com/roots/roots/issues/28 but this is important enough to revisit. 

For example: adding this code to `lib/init.php` Will force all scripts to go to the bottom. Modernizr would have to somehow manually be hoisted to the top.

```php
function custom_clean_head() {
  remove_action('wp_head', 'wp_print_scripts');
  remove_action('wp_head', 'wp_print_head_scripts', 9);
  remove_action('wp_head', 'wp_enqueue_scripts', 1);
}
add_action( 'wp_enqueue_scripts', 'custom_clean_head' );
```

Haven't quite run into any problems with plugin compatibility yet as I only tend to use high-profile and well-maintained plugins. Do you guys want to bark down this tree? It was very very soul crushing to see the fruits of my labor (precompiling assets) being wasted because of the render-blocking jquery in the header.

**Comment by retlehs** [comment]
dropping this here so i don't forget

http://writing.colin-gourlay.com/safely-using-ready-before-including-jquery/

**Comment by austinpray** [comment]
damn that article is p hacky

**Comment by austinpray** [comment]
Fixin tuh make a much better version

**Comment by QWp6t** [comment]
It's also pretty old.

I've never had a need to put scripts somewhere in the middle of the body, so I don't really understand the need for that in the first place. I think if you're having trouble with wanting to use jQuery before jQuery is loaded, then you're doing something wrong. In other words, he's solving a problem that developers shouldn't have in the first place, at least in my opinion.

**Comment by retlehs** [comment]
unfortunately a lot of WordPress plugins do that tho, but I agree

**Comment by grappler** [comment]
@bryanwillis brought this code to my attention as I have a script to load html5.js via the functions.php https://gist.github.com/grappler/05568f05633484499acc#file-wp-4-2-functions-php

@bryanwillis said that your script would break this.

@austinpray or @QWp6t does this code not move all of the *styles* and *scripts* to the footer?

**Comment by QWp6t** [comment]
It does not move styles to the footer. It will break your html5shiv because html5shiv needs to be loaded before layout is rendered. All Soil modules are explicitly loaded by the theme developer, so if a developer's theme is intended to support older versions of IE, then the developer shouldn't load js-to-footer or s/he should come up with an alternative method for loading html5shiv in the head.

**Comment by bryanwillis** [comment]
@grappler , 99% of the time I'm wrong so I wouldn't go around quoting me too often :) ... I'm glad you brought this up though!

As for what @QWp6t said I couldn't  agree more. I think the important thing is that most soil modules should be used by the actual site developer himself/herself, and not implemented in free themes or plugins at this time in respect to Ulrich's Theme review team. A lot of these modules go against  [theme review requirements](https://make.wordpress.org/themes/handbook/review/required/#stylesheets-and-scripts) like loading jquery from a cdn or using google analytics. 

As for HTML5shiv, I've done [a lot of thinking](http://wordpress.stackexchange.com/a/214460/43806
) (undoubtedly [way too much](http://stackoverflow.com/questions/34734100/how-to-use-html5shiv-correctly-how-work-on-ie-9-firefox-safari/34734168?noredirect=1#comment57602302_34734168)) about how it and modernizr should be implemented. Pretty much this is one of the few scripts out there that I know of that HAS TO be loaded in the head to work effectively and part of the reason is due to the css it loads.

HTML5shiv/Modernizr has some conflicting information in it's [readme](https://github.com/aFarkas/html5shiv) on how should be used. The useage tells you to include it like this:

```html
<!--[if lt IE 9]>
    <script src="bower_components/html5shiv/dist/html5shiv.js"></script>
<![endif]--> 
```

It also says that it works for IE 6-9, Firefox 3 and Safari 4, but using the above code it would load in IE5-8. 

The correct way to load it (in my opinion) would be this:

```html
<!DOCTYPE html>
<html>
  <head>
    <!-- HTML5 shiv in head supporting all necessary browsers... You can omit the css if your css reset or theme already include them-->
<style type="text/css">
    article,aside,dialog,figcaption,figure,footer,header,hgroup,main,nav,section{display:block}
    mark{background:#FF0;color:#000}
</style>
<!--[if (gt IE 5)&(lt IE 9)]>
    <script type="text/javascript">window.html5={shivCSS:!1};</script>
    <script type="text/javascript" src="bower_components/html5shiv/dist/html5shiv.js"></script>
<![endif]-->
</head>
```

Considering that Microsoft dropped support for legacy browsers on January 12th, and Firefox and Safari offer automatic updates, I think it's safe for themes to stop supporting html5shiv anyway, but that's just my opinion. If you're using the css, html5shiv would only be supporting about 1% of browsers ( IE6-8 ). 

However, for people that still need to use HTML5shiv and want to use soil, I think including it in the head is an acceptable alternative and might still pass theme review standards since this is a browser workaround script as far as I'm concerned. It also makes the most sense.... a script that MUST be loaded in the head should use `wp_head`. 

```php
add_action('wp_head', 'wp_theme_echo_html5shiv', 99);
function wp_theme_echo_html5shiv() {
    echo ' <!--[if (gt IE 5)&(lt IE 9)]> <script>window.html5={shivCSS:!1};</script> <script src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> <![endif]-->
' . "\n";
}
```

You could do this as I already mentioned to Ulrich but it's probably not needed since this is one of those scripts that has gone by so many names over the years (html5shiv, html5, twentywhatever-html5, shim, modernizr, etc).

```php
if ( wp_script_is( 'html5shiv', 'enqueued' ))
     wp_dequeue_script( 'html5shiv' );
```


Or when using soil with a theme that enqueues the shiv, this below would work, but it's pretty ugly in my opinion :

```php
add_action( 'wp_head', 'wp_theme_check_html5shiv', 1 );
function wp_theme_check_html5shiv() {
    if ( !has_filter( 'wp_head', 'wp_enqueue_scripts' ) && !wp_script_is( 'html5shiv', 'done' ) ) {
        add_action('wp_head', 'wp_theme_echo_html5shiv');
        wp_dequeue_script('html5shiv');
    }
}
function wp_theme_echo_html5shiv() {
    echo '<!--[if (gt IE 5)&(lt IE 9)]> <script>window.html5={shivCSS:!1};</script> <script src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> <![endif]-->' . "\n";
}
```

There's probably other ways to do this like filtering the script loader tag and doing something like [jquery-cdn.php](https://github.com/roots/soil/blob/master/modules/jquery-cdn.php) does, but probably also unecessary. 

I vote we just blackball the shiv from new theme, but that probably won't happen! 

@grappler maybe you guys could add to the theme review guides an example of a browser workaround script. I've brought up a [similar with twenty-sixteen regarding the Paul Irish `no-js` script](https://github.com/WordPress/twentysixteen/issues/408) implemented in a lot of themes. I might be confused on what exactly a browser workaround script actually is, but I think these would both apply.

Anyway, sorry if I got off topic at all here, especially since this is a closed issue.

**Comment by grappler** [comment]
Thanks @QWp6t. I still somehow do not fully understand how this feature works but that is fine as I don't need to.

@bryanwillis Gist is not useful for discussion as there are no notifications. A browser workaround script is something like html5.js. We made an exception as before WP 4.2 there was no way to add the necessary comment data. I would like to get the exception removed on WP 4.5 or 4.6 is released.

If wanted to move all of the scripts to the footer you could do something like this. FYI Wp 4.2+

```php
function grappler_move_js_to_footer() {
	if( is_admin() ) {
		return
	}
	$scripts = wp_scripts();
	foreach( $scripts->registered as $script ) {
		if ( 'html5' == $script->handle ) {
			wp_script_add_data( $script->handle, 'group', 0 );
		} else {
			wp_script_add_data( $script->handle, 'group', 1 );
		}
	}
}
add_action( 'wp_enqueue_scripts', 'grappler_move_js_to_footer', 99 );
```

**Comment by bryanwillis** [comment]
<blockquote> Gist is not useful for discussion as there are no notifications.</blockquote>
....Soooo that's why no one ever replies haha.

@grappler  good thinking with the above btw. 

The only thing I'd change is dropping the `is_admin()` inside the function since `wp_enqueue_scripts` is hooked into `wp_head` on the frontend only. 

You could do something like this I suppose: 

`is_admin() || add_action( … )`

**Comment by bryanwillis** [comment]
I hate to be commenting on a closed issue again. but @grappler when you tested that code were you using the jquery cdn script or your own jquery by chance. After deactivating the soil jquery script, it appears that this isn't printing jquery. It seems that all other scripts are fine though. 

I thought maybe it was a plugin or something so I deactivated and tried with twentysixteen, fifteen, and genesis, but using the `wp_script_add_data` method doesn't seem to include jquery.

**Comment by grappler** [comment]
It seems that there is a bug in WordPress https://core.trac.wordpress.org/ticket/35643

**Comment by bryanwillis** [comment]
Thanks good find!
