### ISSUE TITLE
soil-clean-up removes feed links added by automatic-feed-links

### ISSUE THREAD

**Issue by teohhanhui** [roots/soil#68]
Why are feed links considered "unnecessary"?

**Comment by retlehs** [comment]
thanks for bringing this up. this in one of the older features of the roots theme, and my thoughts [way back then] were "why is there a comments feed automatically added to every page?"

rather than completely removing feed links, we could just remove the comments feed link. then we could add even theme support for `automatic-feed-links` to sage.

**Comment by QWp6t** [comment]
This seems to work.

```php
function head_cleanup() {
  // Originally from http://wpengineer.com/1438/wordpress-header/
  //remove_action('wp_head', 'feed_links', 2);
  remove_action('wp_head', 'feed_links_extra', 3);
  add_action('wp_head', '\ob_start', 1, 0);
  add_action('wp_head', function() {
    $pattern = '/.*' . preg_quote(esc_url(get_feed_link('comments_' . get_default_feed())), '/') . '.*[\r\n]+/';
    echo preg_replace($pattern, '', ob_get_clean());
  }, 3, 0);
 
 // ...

}
```

Make sure to `add_theme_support('automatic-feed-links');` in your theme.

Thoughts?
